---
services:
  opencloud:
      environment:
        # bind to all interfaces
        PROXY_HTTP_ADDR: "0.0.0.0:9200"
      ports:
        # expose the opencloud server on localhost
        - "9200:9200"
